### ISSUE TITLE
Manage the app from an android device

### ISSUE THREAD

**Issue by Marcurio22** [Marcurio22/GESPRO_Practica_2_Curso_2024_2025#12]

**Comment by crimsonCh4os** [comment]
¿ La aplicación estará disponible en la play store ?

**Comment by Marcurio22** [comment]
Sí, la aplicación se encontrará disponible en Android Play Store, para facilitar el acceso al mayor número de usuarios posible y que tenga una forma cómoda y sencilla de acceder a nuestra aplicación.
