### ISSUE TITLE
Set up automatic payment

### ISSUE THREAD

**Issue by Marcurio22** [Marcurio22/GESPRO_Practica_2_Curso_2024_2025#17]

**Comment by aal1021** [comment]
¿Se podrá pagar por  bizum o solo se permite el pago por tarjeta?

**Comment by crimsonCh4os** [comment]
Actualmente, solo se permite el pago por tarjeta. Estamos considerando añadir Bizum en futuras actualizaciones y te mantendremos informado sobre cualquier novedad.
