### ISSUE TITLE
See deposit edition analytics

### ISSUE THREAD

**Issue by crimsonCh4os** [Marcurio22/GESPRO_Practica_2_Curso_2024_2025#28]

**Comment by Marcurio22** [comment]
¿Podré tener acceso a mi historial de depósitos del banco, pudiendo ver la fecha de la realización del mismo?

**Comment by crimsonCh4os** [comment]
Sí, en la aplicación podrás acceder a tu historial de depósitos, donde verás la fecha de cada uno, junto con la cantidad y el estado de la transacción.
