### ISSUE TITLE
Transfer Money

### ISSUE THREAD

**Issue by Marcurio22** [Marcurio22/GESPRO_Practica_2_Curso_2024_2025#5]

**Comment by crimsonCh4os** [comment]
¿Cómo puedo revisar el historial de mis transacciones en la aplicación de mi banco?

**Comment by Marcurio22** [comment]
Habrá una funcionalidad en la aplicación que te permita ver este detalle. En el apartado de transferir dinero, en los tres puntitos de arriba a la derecha se te abrirá un menú y la primera opción que aparecerá será la de: revisar historial de transacciones.
